#
CXX = g++
CXXFLAGS = -g -Wall -Werror -std=gnu++17 -D_GNU_SOURCE

# .cpp	(.cc/.cxx/.C)
# .h	(.hh/-)a

all: 1 2 3 4 5

1 : 1.cpp
2 : 2.cpp
3 : 3.cpp
4 : 4.cpp
5 : 5.cpp

clean:
	rm -f *o
	rm -f 1
	rm -f 2
	rm -f 3
	rm -f 4
	rm -f 5
	rm -f *~
	rm -f .*~
